### ISSUE TITLE
Add functionality to fortunes route

### ISSUE THREAD

**Issue by stevekinney** [stevekinney/feel-good-bot#3]
We have a route that responds to `/fortunes`, but it currently doesn't return anything.

Maybe it should shuffle through an array of fortune and send a random one to the user?

You can probably grab some fortunes from this [random fortune generator](http://www.fortunecookiemessage.com/).

Does anyone else have some ideas for fortune?

**Comment by smbsimon** [comment]
@ianderse, here to review when you're ready

**Comment by okappati** [comment]
@smbsimon, standby

**Comment by ianderse** [comment]
see #8

**Comment by ianderse** [comment]
:squirrel:

**Comment by smbsimon** [comment]
👍
